### ISSUE TITLE
Files are not being processed. 

### ISSUE THREAD

**Issue by wiebereu** [Unmanic/unmanic#183] opened 2021-06-29 01:26 UTC
I ran unmanic version 0.0.8~1cd1e61
The  problem is that i find out yesterday that there are a lot of files still need to process but unmanic is telling me that there is nothing to process at the moment and that the workers are waiting for a job. I restart unmanic to force it to scan the library but to no avail. In the settings i configure the app to scan the library every 360 minutes but still nothing.  All my movies are in sub-folders, i guess when i set the app to scan the parent folder that it will scan the sub-folders as well. I don't know for sure if that is how the app is working. I do know that it converted a lot of movies in the same settings but that now it doesn't do anything. I run unmanic in Docker on a virtual machine which Unmanic is the only container besides Portainer that is running in the VM on Docker. 
[Unmanic logs.txt](https://github.com/Unmanic/unmanic/files/6729977/Unmanic.logs.txt)

**Comment by Josh5** [comment] 2021-06-29 03:21
Unmanic will scan subdirectories.

It looks like you are running the container not as root. The container process does not have the required permissions to configure your directories. Therefore I would determine that this is an issue with your configuration not the docker image or Unmanic itself.

Please check your portainer config and ensure you run the container as root and not "--user"

**Comment by wiebereu** [comment] 2021-06-29 08:07
Well the same configuration i run for months  before and i never had any issue. I don't see why i have to run a container as root to process some movies, while we all know that is not recommended to run containers as root

**Comment by Josh5** [comment] 2021-07-01 00:05
There is evidence in your provided logs that the issue is your file permissions have changed and the Unmanic process inside the container cannot modify them. 
Running the container as root does not run the Unmanic process as root. There is no problems whatsoever in running containers as root if they are designed to do so. Your recommendations are incorrect. If you read the Dockerfile and the log that you provided above and understand them then you will see why you have to run this particular container as root to process some movies. If you are unable to understand a Dockerfile and the logfile you provided, then please do not argue with the advice that I provide you as this only wastes my time.
If you choose not to run the container as it is intended to be run, as you are well within your rights to do so, then please also carry out all issue diagnostics on your own.

I'm closing this issue as it is not valid. Thanks.

**Closed by Josh5** 2021-07-01 00:05 UTC
Labels: invalid
