### ISSUE TITLE
HW acceleration fails – Failed to end picture encode issue: 24 (internal encoding error).

### ISSUE THREAD

**Issue by northtsar** [Unmanic/unmanic#167] opened 2021-04-13 16:00 UTC
### Description

Unmanic was working just fine for me up until watchtower decided to update the container and mixed everything up. After that I freshly installed Unmanic and now HW acceleration (hevc_vaapi) is no longer working. I'm pretty sure that I did everything in the exact same way as before – however, it might just be a stupid little mistake from my side that prevents HW acceleration from working. 

Currently Unmanic is running on a Synology NAS (1520+). The QuickSync GPU is/should be mounted inside the container (I can access it in the /dev/dri folder through the terminal. 

Audio encode is disabled. Advanced settings are both set according to the documentation. 

**Expected behavior:** [What you expect to happen]

Clean hevc_vaapi encode. 

**Actual behaviour:** [What actually happens]

All encodes fail with the same error message:

[hevc_vaapi @ 0x55660db298c0] Failed to end picture encode issue: 24 (internal encoding error).
[hevc_vaapi @ 0x55660db298c0] Encode failed: -5.
Video encoding failed
Conversion failed!

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

Version - 0.0.4~9a575bc

### Installation Method Used

Docker

### Additional Information

Custom options: -vf format=nv12|vaapi,hwupload

**Comment by northtsar** [comment] 2021-04-16 12:07
So I think I finally managed to get HW-Acceleration working again. 

For anyone interested this is what I had to change/add:

- Docker running with "High privileges" (not sure if needed tho, correct me if I am wrong)
- Added an environment variable to the container LIBVA_DRIVER_NAME=i965

Now the encode is running again and does no longer fail at the beginning.

**Comment by Josh5** [comment] 2021-04-19 18:41
That's interesting.

I cannot reproduce these steps of yours as I don't have either a Synology Nas or one of these CPUs.

Could you do me a favour and add some screenshots of your Synology setup? That way I can add it to the documentation for others.

**Comment by northtsar** [comment] 2021-04-21 12:28
Sure, let me give this a try. Let me know if you need anything else. 

### Synology container setup

![Screenshot 2021-04-21 at 12 52 43](https://user-images.githubusercontent.com/82463018/115551521-1f187e80-a2a3-11eb-8857-82b0b3147ae1.jpg)
- Enable high privilege
- Resource limitation is optional
- Auto-restart is optional

![Screenshot 2021-04-21 at 12 53 30](https://user-images.githubusercontent.com/82463018/115551687-5555fe00-a2a3-11eb-9596-acc514d132cb.jpg)
- The /video mount points to your video library which you want to be able to access in Unmanic

![Screenshot 2021-04-21 at 12 54 08](https://user-images.githubusercontent.com/82463018/115551815-7c143480-a2a3-11eb-9c55-91f3f2b990be.jpg)
- Local Port 8888 can be changed to whatever you prefer. Example: If set to "38888" the Web-UI will be accessible on port 38888 (_serverip:38888_). 

![Screenshot 2021-04-21 at 12 56 05](https://user-images.githubusercontent.com/82463018/115552123-d31a0980-a2a3-11eb-81e4-a69df4a8173f.jpg)
![Screenshot 2021-04-21 at 12 56 18](https://user-images.githubusercontent.com/82463018/115552133-d6ad9080-a2a3-11eb-8f41-6d8084643b6c.jpg)
- Set your PID and GID
- Set your TZ 
- Add the LIBVA_DRIVER_NAME variable. Set to i965.

**Finish setting up the container and run for the first time. Check if everything's running properly.** 

### Adding HW-Acceleration capabilities

Stop the container and export the settings to your local computer. Delete the container afterwards.
<img width="175" alt="Screenshot 2021-04-21 at 13 08 21" src="https://user-images.githubusercontent.com/82463018/115552502-520f4200-a2a4-11eb-875e-b464aebfe7ed.png">
<img width="551" alt="Screenshot 2021-04-21 at 13 08 47" src="https://user-images.githubusercontent.com/82463018/115552512-55a2c900-a2a4-11eb-806b-c3ed7160441f.png">

In the freshly downloaded .json file add the following text as shown in the picture: 
"devices": [{"CgroupPermissions": "rwm", "PathInContainer": "\/dev\/dri", "PathOnHost": "\/dev\/dri"}],

<img width="657" alt="Screenshot 2021-04-21 at 13 10 24" src="https://user-images.githubusercontent.com/82463018/115552741-8b47b200-a2a4-11eb-86ac-bbfe0c21a874.png">

Import the modified .json file to your Synology NAS Docker Station and run the container. 

**Finish setting up HW-Acceleration by following the advanced section of the documentation. Make sure to set the additional variables and enable HW-Acceleration in the Web-UI settings.**

**Comment by northtsar** [comment] 2021-04-21 12:29
Hope this helps @Josh5. Thanks for the awesome work put into this!

**Comment by Josh5** [comment] 2021-04-21 12:46
Yea. Thanks!

That's really interesting that you need to export the config and manually add the devices. Is this a common trick with other containers such as Plex?

**Comment by northtsar** [comment] 2021-04-21 12:53
Yes, exactly. Had to do the same to get HW-transcoding working with Plex. 
I think this step is not needed when setting up the container using CLI – there you can mount the drivers directly.

**Comment by Josh5** [comment] 2021-09-20 02:28
I'm adding this to the docs now...
Just a quick question on this..

In your last image you have the PathOnHost value escaped. Eg. `\/dev\/dri`. 
Why does that need to be escaped?

**Comment by Josh5** [comment] 2021-09-20 02:36
(closing as docs have been added... https://docs.unmanic.app/docs/installation/synology/)

**Closed by Josh5** 2021-09-20 02:36 UTC
