### ISSUE TITLE
Unknown FrameType

### ISSUE THREAD

**Issue by mlavio829** [Unmanic/unmanic#320] opened 2022-04-08 00:36 UTC
Hi,
I'm experiencing some issues with unmanic. I'm getting an unknown frame type error when using hevc_qsv with an Intel i5-11400 CPU. Any ideas?

Metadata:
encoder : Lavf58.45.100
Stream #0:0(eng): Video: hevc (hevc_qsv), qsv, 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 1000 kb/s, 23.98 fps, 1k tbn, 23.98 tbc (default)
Metadata:
encoder : Lavc58.91.100 hevc_qsv
Side data:
cpb: bitrate max/min/avg: 0/0/1000000 buffer size: 0 vbv_delay: N/A
Stream #0:1(eng): Audio: dts (DTS) ([1] [0][0] / 0x2001), 48000 Hz, 5.1(side), fltp, 1536 kb/s (default)
[hevc_qsv @ 0x55902d61dc40] Unknown FrameType, set pict_type to AV_PICTURE_TYPE_NONE.

**Comment by nicolas-schreiber** [comment] 2022-05-20 13:24
Got the same problem here, were you able to solve it?

**Comment by Josh5** [comment] 2022-05-21 21:10
Have you tried googling this error? What results did you find?

This error is not from Unmanic, it is with FFmpeg. Therefore the issue is that the file you are trying to process cannot be processed in the way you have configured the Unmanic plugin.

If you need support for configuration of unmanic, I suggest joining the discord server and asking for help there first.


I'm closing this issue as it has nothing to do with this git repo and there is nothing for me to do here.

**Closed** 2022-05-21 21:10 UTC
