### ISSUE TITLE
Plex registering empty files

### ISSUE THREAD

**Issue by blddk** [Unmanic/unmanic#120] opened 2020-07-25 16:58 UTC
I started by having my temp dir on /tmp/ in unraid, but this caused some problems after encoding of a file had finished.

When unmanic started to move the file over to the array, plex noticed the file as soon as it was created, but still empty. This caused multiple files to get merged into the same movie, even when they were different movies. The reason for this could be that plex create a checksum for the empty file, remembers that and never update it again, and next time it sees an empty file, the checksum will match the previous empty file.

~~One fix for this, is to have the tmp dir on the same array as the file encoded. This will make it appear instantly in its full size on the target path after encoding.~~
Looks like that isn't even what is going on, it seems to be copying the file over. A faster approach would be to move it from the temp path to the final path. That way it would appear instantly on the final path, and also cause less wear on drives.

Another fix could be to move it with .tmp extension, then just rename it to ex. .mp4 (or what ever selected) after the encoded file has been copied.

**Comment by blddk** [comment] 2020-07-25 19:04
I did some digging, and found it is already moving the file, and not copying. Or at least it is moving here https://github.com/Josh5/unmanic/blob/master/unmanic/libs/postprocessor.py#L111

I currently got Version - 0.0.1-beta7+1a6d561 on unraid, is it moving in that one too? If it does, I am puzzled why the file is getting moved just as slow as it is to copy it, when it is on the same array already. Making a little test script doing the same, just makes the file disappear in one folder, and appear in the other right away.

**Comment by Josh5** [comment] 2021-07-29 19:44
Just for an FYI, the reason why the move process is as slow as a copy is because it is a copy.
The move command will only rename the file point to a new location if the move process happened on the same disk. And array is made up of multiple disks and in your case you will be moving files from one disk to another on the same array. For this reason the move process first copies the while file and then on successful completion of that copy it removes the original source file.

I believe that the best solution is to do a double move as you say that first names it as a partial movement with a custom file extension and then renames the file to the final extension.

**Comment by Josh5** [comment] 2021-09-20 01:38
I dont think there is a simple fix for this. If it is an issue with Plex, there is a plugin to trigger plex updates rather than enable the plex file watcher.

Closing as this is not a bug exactly and there is no real fix from an Unmanic point of view. The issue with moving files between disks is not specific to Unmanic. This will happen for any application that carries out a move operation on your array.

**Closed by Josh5** 2021-09-20 01:38 UTC
Labels: bug
